version: '3.7'

networks:
  backend:

volumes:
  my-db:
      driver: local

services:
  mysql:
      image: mysql:8.0.19
      container_name: 'keycloak_db'
      restart: always
      volumes:
        - my-db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
      ports:
        - 33060:3306
      networks:
        backend:
  keycloak:
      image: jboss/keycloak:latest
      container_name: 'keycloak'
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        JDBC_PARAMS: "connectTimeout=30000&useSSL=false&allowPublicKeyRetrieval=true"
      networks:
        backend:
      ports:
        - 8080:8080
      depends_on:
        - mysql
